### ISSUE TITLE
[Bug] Get started commands results in DB failure on clean install

### ISSUE THREAD

**Issue by Swordworx** [teamgeek-io/flask-blog-starter#3]
### Problem

Following the [get started](https://github.com/teamgeek-io/flask-blog-starter#get-started) section of the readme results in a DB failure.

Running the commands `make dev_install` && `make run` throws the following error:

```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: posts
[SQL: SELECT posts.id AS posts_id, posts.title AS posts_title, posts.content AS posts_content, posts.created_at AS posts_created_at, posts.updated_at AS posts_updated_at
```

### Environment

MacOS version 11.2.3
Python version 3.9.2

### Temporary fix

My workaround was to create a DB using `make shell`:

```py
from flask_blog.database import db
db.create_all()
```

After that I could run `make init_db` and the app runs without issue.

### Proposed solution

I'm not a python developer so I'm unsure what the solution would be. 😅 The ideal would be to resolve this as part of `dev_install` or add a new command to create a DB under the `get started` section of the readme.

**Comment by sluipmoord** [comment]
@Swordworx Thank you for picking up this issue. I made a PR  to fix readme with the correct instructions
